-- CVC Circle Startups Seed Data
-- Run this in Supabase SQL Editor
-- These startups were reviewed in CVC & POC Circle meetings

INSERT INTO startups (name, slug, sector, stage, description_tr, description_en, founded_year, location, website, tags, status, featured, funding_status)
VALUES
-- POC + Invested startups (highlighted)
('Shippn', 'shippn', 'Logistics', 'growth', 'Uluslararası e-ticaret gönderi ve kargo çözümleri sunan lojistik platformu.', 'International e-commerce shipping and logistics platform connecting shoppers worldwide.', 2015, 'Istanbul', 'https://shippn.com', ARRAY['logistics','e-commerce','shipping'], 'approved', true, 'funded'),
('Pivony', 'pivony', 'AI/Analytics', 'seed', 'Müşteri görüşlerini analiz eden omnichannel yapay zeka platformu. Derin sinir ağı dil işleme teknolojisi kullanır.', 'Omnichannel consumer intelligence platform using deep neural language processing to analyze millions of conversations.', 2020, 'Istanbul', 'https://www.pivony.com', ARRAY['ai','analytics','nlp'], 'approved', true, 'funded'),
('Jobtogo', 'jobtogo', 'HR/Freelance', 'seed', 'İşverenler ve serbest çalışanları birbirine bağlayan platform. Güvenli ödemeler ve kontrat yönetimi sunar.', 'Platform connecting employers with freelancers. Offers secure payments, contracts and invoice management.', NULL, 'Istanbul', 'https://www.jobtogo.co', ARRAY['hr','freelance','marketplace'], 'approved', true, 'funded'),
('Bren', 'bren', 'Industrial IoT', 'seed', 'Sanayi alanlarında bataryasız akıllı sensörleri ile enerji tasarrufu ve bakım optimizasyonu sağlar.', 'AI-based industrial IoT company with battery-free sensor technology for manufacturing monitoring.', NULL, 'Istanbul', NULL, ARRAY['iot','manufacturing','sensors'], 'approved', true, 'no_funding'),
('Empler AI', 'empler-ai', 'AI/Automation', 'pre-seed', 'İşletmeler için agentic AI otomasyon platformu. 35+ dilde AI tabanlı görev yönetim araçları sunuyor.', 'Cloud-based AI task management platform for enterprises. AI-powered automation tools supporting 35+ languages.', 2023, 'Istanbul', 'https://www.empler.ai', ARRAY['ai','automation','saas'], 'approved', true, 'raising'),
('Harcy', 'harcy', 'Sustainability/Materials', 'seed', 'Tekstil atıklarından yüksek kaliteli yalıtım malzemeleri üreten teknoloji şirketi. Dairesel ekonomiye katkı sağlıyor.', 'Converts textile waste into high-quality insulation materials for construction. Patented circular economy technology.', 2022, 'Istanbul', 'https://harcy.com.tr', ARRAY['sustainability','circular-economy','construction'], 'approved', true, 'raising'),
('Packard', 'packard', 'Technology', 'seed', 'POC sürecinden geçmiş teknoloji girişimi.', 'Technology startup that went through the POC process.', NULL, 'Istanbul', NULL, ARRAY['technology'], 'approved', false, 'no_funding'),

-- Reviewed startups
('Sensgreen', 'sensgreen', 'IoT/Smart Buildings', 'series-a', 'Ticari binaların enerji, hava kalitesi ve sürdürülebilirliğini yapay zeka ile optimize eden IoT şirketi.', 'IoT company using AI to optimize energy, air quality, and sustainability in commercial buildings.', 2018, 'Ankara', 'https://sensgreen.com', ARRAY['iot','smart-buildings','energy'], 'approved', false, 'funded'),
('Wefarm', 'wefarm', 'AgriTech', 'pre-seed', 'Boş arazileri teknoloji kontrollü tarım sistemleri ile üretken alanlara dönüştüren platform.', 'Agriculture technology platform converting unused land into productive farms using tech-controlled systems.', 2022, 'Istanbul', 'https://wefarm.com.tr', ARRAY['agritech','farming'], 'approved', false, 'raising'),
('Worksy', 'worksy', 'HR/Workforce', 'seed', 'İş gücü yönetimi ve işe alım süreçlerini optimize eden platform.', 'Platform optimizing workforce management and recruitment processes for businesses.', NULL, 'Istanbul', NULL, ARRAY['hr','workforce'], 'approved', false, 'no_funding'),
('Bulutklinik', 'bulutklinik', 'HealthTech', 'growth', 'Doktorların kliniklerini yönetmesine ve hasta verilerini takip etmesine olanak sağlayan çevrimiçi sağlık platformu.', 'Online health platform enabling doctors to manage clinics and telemedicine with millions of patients served.', 2016, 'Istanbul', 'https://bulutklinik.com', ARRAY['healthtech','telemedicine'], 'approved', false, 'funded'),
('Onedocs', 'onedocs', 'LegalTech', 'seed', 'Yapay zeka destekli sözleşme analizi ve yaşam döngüsü yönetimi yazılımı.', 'AI-powered contract analysis and lifecycle management platform for enterprises.', 2019, 'Istanbul', 'https://onedocs.com', ARRAY['legaltech','ai','contracts'], 'approved', false, 'raising'),
('Fizbot', 'fizbot', 'PropTech', 'seed', 'Gayrimenkul danışmanlarına yardımcı olan yapay zeka tabanlı satış ve yönetim platformu.', 'AI-powered sales management platform for real estate brokers for lead tracking.', 2017, 'Istanbul', 'https://fizbot.net', ARRAY['proptech','real-estate','ai'], 'approved', false, 'funded'),
('Wastelog', 'wastelog', 'CleanTech', 'seed', 'Atık kaynakları ile lisanslı toplama şirketlerini bağlayarak geri dönüşüm sürecini dijitalleştiren platform.', 'Digital waste management platform connecting waste producers with licensed recycling companies.', NULL, 'Istanbul', 'https://wastelog.co', ARRAY['cleantech','recycling','waste'], 'approved', false, 'raising'),
('Nuvio', 'nuvio', 'FinTech', 'seed', 'Yapay zeka destekli finansal analitik ve raporlama platformu ile KOBİlere dijital CFO hizmetleri sağlar.', 'AI-powered digital CFO platform providing financial analytics and cash flow management for SMEs.', NULL, 'Istanbul', 'https://nuvio.io', ARRAY['fintech','ai','analytics'], 'approved', false, 'raising'),
('Voltla', 'voltla', 'ClimateTech/EV', 'seed', 'Elektrikli araçlar için şarj istasyonu erişimini ve ödeme yönetimini kolaylaştıran mobil platform.', 'Mobile platform simplifying EV charging by aggregating multiple charging providers in one app.', 2022, 'Istanbul', 'https://voltla.com.tr', ARRAY['ev','charging','climatetech'], 'approved', false, 'raising'),
('Arkeobox', 'arkeobox', 'EdTech/Gaming', 'seed', 'Çocuklara kültürel mirasa yönelik farkındalık kazandıran eğitici masa oyunları ve kazı kitleri üreten şirket.', 'Educational board game and excavation kit producer raising cultural heritage awareness.', NULL, 'Istanbul', NULL, ARRAY['edtech','gaming','culture'], 'approved', false, 'no_funding'),
('OMMA', 'omma', 'MarTech/Digital Signage', 'series-a', 'Dijital tabela ve kişiselleştirilmiş video içeriği için akıllı ekran motoru kullanan iletişim platformu.', 'Display-based marketing platform providing digital signage and personalized video content solutions.', 2015, 'Istanbul', 'https://ommasign.com', ARRAY['martech','digital-signage'], 'approved', false, 'funded'),
('Robolaunch', 'robolaunch', 'Robotics', 'seed', 'ROS/ROS 2 robotlarını ölçekte geliştirmek ve işletmek için bulut-yerel robotik platformu.', 'Cloud-native robotics platform for developing, deploying, and operating ROS/ROS 2 robots at scale.', 2020, 'Ankara', 'https://robolaunch.io', ARRAY['robotics','cloud','ros'], 'approved', false, 'raising'),
('Paywall', 'paywall-one', 'FinTech/Payments', 'seed', 'Türkiyenin ilk ödeme orkestrasyonu platformu. Akıllı yönlendirme ve ödeme kurtarma hizmetleri sunar.', 'Turkey''s first payment orchestration platform offering smart routing and fraud detection.', 2022, 'Istanbul', 'https://paywall.one', ARRAY['fintech','payments'], 'approved', false, 'raising'),
('CogniScope', 'cogniscope', 'Gaming/AI', 'seed', 'Oyuncu geri bildirimlerini analiz eden yapay zeka platformu. Oyun geliştiricilere memnuniyet analizi sunar.', 'AI platform analyzing player feedback data for game developers to drive engagement and retention.', NULL, 'London', 'https://cogniscope.com', ARRAY['gaming','ai','analytics'], 'approved', false, 'raising'),
('GoWit', 'gowit', 'AdTech/Retail', 'growth', 'Retail Media Ads platformu. Marketplaces''lere marka reklam ve satış araçları sunan AI odaklı şirket.', 'AI-powered retail media advertising platform for marketplaces.', NULL, 'Istanbul', 'https://gowit.com', ARRAY['adtech','retail','ai'], 'approved', false, 'funded'),
('Lumnion', 'lumnion', 'InsurTech/AI', 'seed', 'Sigorta endüstrisine AI tabanlı fiyatlandırma platformu. Risk modelleme ve davranışsal fiyatlandırma sunar.', 'AI-based pricing platform for non-life and health insurance with risk modeling.', 2016, 'Istanbul', 'https://www.lumnion.com', ARRAY['insurtech','ai','pricing'], 'approved', false, 'funded'),
('etasin', 'etasin', 'Logistics/Moving', 'seed', 'Ev ve ofis taşınması için AI tabanlı platform. Şehir içi ve şehirler arası hizmetler sunar.', 'AI-based relocation platform for home and office moving services across Turkey.', 2020, 'Istanbul', 'https://etasin.com', ARRAY['logistics','moving','ai'], 'approved', false, 'raising'),
('Mocky.AI', 'mocky-ai', 'Fashion/AI', 'pre-seed', 'Yapay zeka destekli moda modeli ve görüntü oluşturma platformu. E-ticaret için sanal model denemesi sağlar.', 'AI fashion model generator for e-commerce creating professional product photos.', 2023, 'Istanbul', 'https://mocky.ai', ARRAY['fashion','ai','e-commerce'], 'approved', false, 'raising'),
('Nara XR', 'nara-xr', 'EdTech/XR', 'growth', 'Metaverse eğitimi için AR/VR teknolojileri geliştiren startup. İnteraktif öğrenme deneyimleri sunar.', 'Develops XR and AR educational technologies for metaverse learning experiences.', 2017, 'Istanbul', 'https://nara.com.tr', ARRAY['edtech','xr','metaverse'], 'approved', false, 'funded'),
('RNV Analytics', 'rnv-analytics', 'AI/Retail', 'seed', 'Perakende sektörü için yapay zeka tabanlı envanter optimizasyon ve talep tahmini platformu.', 'AI-powered inventory optimization and demand forecasting platform for retail.', 2020, 'Istanbul', NULL, ARRAY['ai','retail','analytics'], 'approved', false, 'raising'),
('SeleKt AI', 'selekt-ai', 'AI/Startup Intelligence', 'pre-seed', 'Girişim ekosistemini takip eden yapay zeka destekli platform. Startupları tanımlar ve puanlandırır.', 'AI-powered startup scouting platform that identifies, analyzes and scores emerging startups.', 2024, 'Istanbul', 'https://selektai.com', ARRAY['ai','startup-scouting'], 'approved', false, 'raising'),
('Econtech', 'econtech', 'FinTech', 'growth', 'Finans yazılımı ve uyum çözümleri sağlayan şirket. AI ile finansal işlemleri kolaylaştırıyor.', 'Financial software and compliance solutions provider using AI and ML.', NULL, 'Istanbul', 'https://econtech.com.tr', ARRAY['fintech','compliance','ai'], 'approved', false, 'funded'),
('Ecomercek', 'ecomercek', 'Health/Wellness', 'pre-seed', 'Kozmetik ve kişisel bakım ürünlerinin çevre ve sağlık etkilerini değerlendiren platform.', 'Platform evaluating environmental and health effects of cosmetics and personal care products.', 2021, 'Istanbul', 'https://www.ecomercek.com', ARRAY['health','sustainability','consumer'], 'approved', false, 'no_funding'),
('WeBee', 'webee', 'Hospitality/Travel', 'growth', 'Otellere konuklarına mükemmel deneyimler sunmak için tasarlanmış 360 derece çözüm platformu.', 'Guest-facing experience solution for hotels enabling outstanding experiences and revenue growth.', 2017, 'Istanbul', 'https://www.getwebee.com', ARRAY['hospitality','travel','saas'], 'approved', false, 'funded'),
('Selfweller', 'selfweller', 'HealthTech/AI', 'pre-seed', 'Yapay zeka kullanan kişiselleştirilmiş öz-terapi ve mindfulness uygulaması.', 'AI-powered self-therapy and mindfulness app with personalized sessions by mental health professionals.', 2023, 'Istanbul', NULL, ARRAY['healthtech','ai','wellness'], 'approved', false, 'raising'),
('Rentiva', 'rentiva', 'Shared Mobility', 'series-a', 'Kişiden kişiye araba paylaşım platformu olarak araç sahipleri ve kiracılarını birleştiriyor.', 'Peer-to-peer car sharing platform connecting vehicle owners with renters.', 2017, 'Istanbul', 'https://rentiva.com', ARRAY['mobility','car-sharing','marketplace'], 'approved', false, 'funded'),
('Tamamlıyo', 'tamamliyo', 'InsurTech', 'seed', 'Sigorta şirketlerini dijital işletmelerle entegre eden sigorta teknoloji platformu.', 'Insurance technology platform integrating insurance companies with digital businesses.', NULL, 'Istanbul', NULL, ARRAY['insurtech','insurance'], 'approved', false, 'raising'),
('Prozon', 'prozon', 'HR/Payroll', 'growth', 'İnsan kaynakları ve bordro yönetimi çözümleri sağlayan kurumsal teknoloji şirketi.', 'HR and payroll management solutions provider for corporate organizations.', NULL, 'Istanbul', 'https://prozon.net', ARRAY['hr','payroll','enterprise'], 'approved', false, 'funded'),
('Poliark', 'poliark', 'AI/Architecture', 'seed', 'Metinden 3D bina tasarımı oluşturan yapay zeka teknolojisi geliştiren startup.', 'Develops text-to-3D AI that creates complex building designs from text descriptions.', 2022, 'Istanbul', NULL, ARRAY['ai','architecture','3d'], 'approved', false, 'raising'),
('Kybeles Garden', 'kybeles-garden', 'Biotech/Agriculture', 'seed', 'Mikroalgler kullanarak tarım, gıda ve kozmetik sektörleri için sürdürülebilir ürünler geliştiriyor.', 'Develops sustainable biotech products using algae for agriculture, food, and cosmetics.', 2021, 'Ankara', 'https://kybelesgarden.com', ARRAY['biotech','agriculture','algae'], 'approved', false, 'raising'),
('Archis Academy', 'archis-academy', 'EdTech', 'seed', 'Yeni mezunlar ve kariyer değiştirenleri yazılım geliştirme alanında eğiten çevrimiçi platform.', 'Online training platform for software development education for graduates and career switchers.', 2019, 'Eskisehir', 'https://archisacademy.com', ARRAY['edtech','software','training'], 'approved', false, 'no_funding'),
('Arvis', 'arvis', 'Gaming', 'seed', 'Orta-çekirdek oyunlar geliştiren ve yayınlayan Türk oyun stüdyosu.', 'Turkish gaming studio creating and publishing mid-core games.', 2019, 'Istanbul', 'https://arvisgames.com', ARRAY['gaming','mobile'], 'approved', false, 'raising'),
('Skann', 'skann', 'AI/Automotive', 'pre-seed', 'Otomotiv endüstrisinde yapay zeka ve bilgisayar görüşü ile muayene yönetimi çözümleri sunuyor.', 'Uses AI and computer vision for automotive inspection management solutions.', NULL, 'Ankara', NULL, ARRAY['ai','automotive','computer-vision'], 'approved', false, 'raising'),
('B2metric', 'b2metric', 'AI/Data Analytics', 'seed', 'İşletmelere müşteri davranışlarını analiz etmek ve tahmin etmek için AI/ML destekli platform.', 'AI/ML-powered data analytics platform analyzing customer behaviors and predicting future actions.', 2017, 'Istanbul', 'https://b2metric.com', ARRAY['ai','analytics','ml'], 'approved', false, 'funded'),
('Cowealth', 'cowealth', 'AgriTech/IoT', 'seed', 'Süt çiftlikleri için IoT ve yapay zeka tabanlı canlı hayvan izleme teknolojileri geliştiriyor.', 'IoT and AI-based livestock monitoring technology for smart dairy farm management.', 2020, 'Kocaeli', NULL, ARRAY['agritech','iot','livestock'], 'approved', false, 'raising'),
('Ni-Cat Batarya', 'ni-cat-batarya', 'Energy/Battery', 'series-a', 'Yeni nesil pil malzemeleri geliştirmek için yapay zeka destekli araştırma yapan şirket.', 'Develops next-generation battery materials with AI-assisted R&D.', 2020, 'Izmir', 'https://nicat.co', ARRAY['energy','battery','deeptech'], 'approved', false, 'funded'),
('REBEE', 'rebee', 'EdTech/Wellness', 'seed', 'Uzman psikologlar tarafından hazırlanan içeriklerle ebeveynlerin çocuklarıyla ilişkilerini geliştiren uygulama.', 'Mobile app with expert-created content helping parents improve relationships with their children.', NULL, 'Izmir', NULL, ARRAY['edtech','parenting','wellness'], 'approved', false, 'no_funding'),
('F-Ray', 'f-ray', 'FinTech', 'seed', 'Finansal belgeleri analiz ederek risk analizi raporları üreten yapay zeka platformu.', 'Financial analysis platform interpreting complex data and generating risk analysis reports.', 2020, 'Ankara', 'https://f-rayfintech.com', ARRAY['fintech','ai','risk-analysis'], 'approved', false, 'raising')

ON CONFLICT (slug) DO NOTHING;
